stacks:
  # TODO: figure out how to handle region naming suffixes
  RelengNetworkUsw1:
    region: us-west-1
    template: network.py
    options:
      region: usw1

  ITUsw1:
    region: us-west-1
    template: it.py
    options:
      vpcid:
        stack: RelengNetworkUsw1
        resource: RelengVPC

  RelengWebUsw1:
    region: us-west-1
    template: relengweb.py
    options:
      region: usw1
      vpcid:
        stack: RelengNetworkUsw1
        resource: RelengVPC
      private_subnet:
        stack: RelengNetworkUsw1
        resource: SubnetPrivate1

# vim: set ts=2 sw=2:
